xn--80aehbh5agfgtdddke8b3a0f6b.xn--p1ai [Wed May 03 06:54:02 2023] [error] [pid 16410] src/server/mod_wsgi.c(3692): [client 185.252.250.154:49554] mod_wsgi (pid=16410): Target WSGI script '/home/c/ct88349/UnionMasters/public_html/UM/UM/wsgi.py' cannot be loaded as Python module.
xn--80aehbh5agfgtdddke8b3a0f6b.xn--p1ai [Wed May 03 06:54:02 2023] [error] [pid 16410] src/server/wsgi_logger.c(630): [client 185.252.250.154:49554] mod_wsgi (pid=16410): Exception occurred processing WSGI script '/home/c/ct88349/UnionMasters/public_html/UM/UM/wsgi.py'.
xn--80aehbh5agfgtdddke8b3a0f6b.xn--p1ai [Wed May 03 06:54:02 2023] [error] [pid 16410] src/server/wsgi_logger.c(147): [client 185.252.250.154:49554] Traceback (most recent call last):
xn--80aehbh5agfgtdddke8b3a0f6b.xn--p1ai [Wed May 03 06:54:02 2023] [error] [pid 16410] src/server/wsgi_logger.c(147): [client 185.252.250.154:49554]   File "/home/c/ct88349/UnionMasters/public_html/UM/UM/wsgi.py", line 16, in <module>
xn--80aehbh5agfgtdddke8b3a0f6b.xn--p1ai [Wed May 03 06:54:02 2023] [error] [pid 16410] src/server/wsgi_logger.c(147): [client 185.252.250.154:49554]     application = get_wsgi_application()
xn--80aehbh5agfgtdddke8b3a0f6b.xn--p1ai [Wed May 03 06:54:02 2023] [error] [pid 16410] src/server/wsgi_logger.c(147): [client 185.252.250.154:49554]   File "/home/c/ct88349/UnionMasters/venv/lib/python3.6/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
xn--80aehbh5agfgtdddke8b3a0f6b.xn--p1ai [Wed May 03 06:54:02 2023] [error] [pid 16410] src/server/wsgi_logger.c(147): [client 185.252.250.154:49554]     django.setup(set_prefix=False)
xn--80aehbh5agfgtdddke8b3a0f6b.xn--p1ai [Wed May 03 06:54:02 2023] [error] [pid 16410] src/server/wsgi_logger.c(147): [client 185.252.250.154:49554]   File "/home/c/ct88349/UnionMasters/venv/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
xn--80aehbh5agfgtdddke8b3a0f6b.xn--p1ai [Wed May 03 06:54:02 2023] [error] [pid 16410] src/server/wsgi_logger.c(147): [client 185.252.250.154:49554]     apps.populate(settings.INSTALLED_APPS)
xn--80aehbh5agfgtdddke8b3a0f6b.xn--p1ai [Wed May 03 06:54:02 2023] [error] [pid 16410] src/server/wsgi_logger.c(147): [client 185.252.250.154:49554]   File "/home/c/ct88349/UnionMasters/venv/lib/python3.6/site-packages/django/apps/registry.py", line 91, in populate
xn--80aehbh5agfgtdddke8b3a0f6b.xn--p1ai [Wed May 03 06:54:02 2023] [error] [pid 16410] src/server/wsgi_logger.c(147): [client 185.252.250.154:49554]     app_config = AppConfig.create(entry)
xn--80aehbh5agfgtdddke8b3a0f6b.xn--p1ai [Wed May 03 06:54:02 2023] [error] [pid 16410] src/server/wsgi_logger.c(147): [client 185.252.250.154:49554]   File "/home/c/ct88349/UnionMasters/venv/lib/python3.6/site-packages/django/apps/config.py", line 224, in create
xn--80aehbh5agfgtdddke8b3a0f6b.xn--p1ai [Wed May 03 06:54:02 2023] [error] [pid 16410] src/server/wsgi_logger.c(147): [client 185.252.250.154:49554]     import_module(entry)
xn--80aehbh5agfgtdddke8b3a0f6b.xn--p1ai [Wed May 03 06:54:02 2023] [error] [pid 16410] src/server/wsgi_logger.c(147): [client 185.252.250.154:49554]   File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
xn--80aehbh5agfgtdddke8b3a0f6b.xn--p1ai [Wed May 03 06:54:02 2023] [error] [pid 16410] src/server/wsgi_logger.c(147): [client 185.252.250.154:49554]     return _bootstrap._gcd_import(name[level:], package, level)
xn--80aehbh5agfgtdddke8b3a0f6b.xn--p1ai [Wed May 03 06:54:02 2023] [error] [pid 16410] src/server/wsgi_logger.c(147): [client 185.252.250.154:49554]   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
xn--80aehbh5agfgtdddke8b3a0f6b.xn--p1ai [Wed May 03 06:54:02 2023] [error] [pid 16410] src/server/wsgi_logger.c(147): [client 185.252.250.154:49554]   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
xn--80aehbh5agfgtdddke8b3a0f6b.xn--p1ai [Wed May 03 06:54:02 2023] [error] [pid 16410] src/server/wsgi_logger.c(147): [client 185.252.250.154:49554]   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
xn--80aehbh5agfgtdddke8b3a0f6b.xn--p1ai [Wed May 03 06:54:02 2023] [error] [pid 16410] src/server/wsgi_logger.c(147): [client 185.252.250.154:49554] ModuleNotFoundError: No module named 'debug_toolbar'
xn--80aehbh5agfgtdddke8b3a0f6b.xn--p1ai [Wed May 03 06:59:56 2023] [error] [pid 56768] src/server/mod_wsgi.c(3692): [client 185.252.250.154:48440] mod_wsgi (pid=56768): Target WSGI script '/home/c/ct88349/UnionMasters/public_html/UM/UM/wsgi.py' cannot be loaded as Python module.
xn--80aehbh5agfgtdddke8b3a0f6b.xn--p1ai [Wed May 03 06:59:56 2023] [error] [pid 56768] src/server/wsgi_logger.c(630): [client 185.252.250.154:48440] mod_wsgi (pid=56768): Exception occurred processing WSGI script '/home/c/ct88349/UnionMasters/public_html/UM/UM/wsgi.py'.
xn--80aehbh5agfgtdddke8b3a0f6b.xn--p1ai [Wed May 03 06:59:56 2023] [error] [pid 56768] src/server/wsgi_logger.c(147): [client 185.252.250.154:48440] Traceback (most recent call last):
xn--80aehbh5agfgtdddke8b3a0f6b.xn--p1ai [Wed May 03 06:59:56 2023] [error] [pid 56768] src/server/wsgi_logger.c(147): [client 185.252.250.154:48440]   File "/home/c/ct88349/UnionMasters/public_html/UM/UM/wsgi.py", line 16, in <module>
xn--80aehbh5agfgtdddke8b3a0f6b.xn--p1ai [Wed May 03 06:59:56 2023] [error] [pid 56768] src/server/wsgi_logger.c(147): [client 185.252.250.154:48440]     application = get_wsgi_application()
xn--80aehbh5agfgtdddke8b3a0f6b.xn--p1ai [Wed May 03 06:59:56 2023] [error] [pid 56768] src/server/wsgi_logger.c(147): [client 185.252.250.154:48440]   File "/home/c/ct88349/UnionMasters//venv/lib/python3.6/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
xn--80aehbh5agfgtdddke8b3a0f6b.xn--p1ai [Wed May 03 06:59:56 2023] [error] [pid 56768] src/server/wsgi_logger.c(147): [client 185.252.250.154:48440]     django.setup(set_prefix=False)
xn--80aehbh5agfgtdddke8b3a0f6b.xn--p1ai [Wed May 03 06:59:56 2023] [error] [pid 56768] src/server/wsgi_logger.c(147): [client 185.252.250.154:48440]   File "/home/c/ct88349/UnionMasters//venv/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
xn--80aehbh5agfgtdddke8b3a0f6b.xn--p1ai [Wed May 03 06:59:56 2023] [error] [pid 56768] src/server/wsgi_logger.c(147): [client 185.252.250.154:48440]     apps.populate(settings.INSTALLED_APPS)
xn--80aehbh5agfgtdddke8b3a0f6b.xn--p1ai [Wed May 03 06:59:56 2023] [error] [pid 56768] src/server/wsgi_logger.c(147): [client 185.252.250.154:48440]   File "/home/c/ct88349/UnionMasters//venv/lib/python3.6/site-packages/django/apps/registry.py", line 91, in populate
xn--80aehbh5agfgtdddke8b3a0f6b.xn--p1ai [Wed May 03 06:59:56 2023] [error] [pid 56768] src/server/wsgi_logger.c(147): [client 185.252.250.154:48440]     app_config = AppConfig.create(entry)
xn--80aehbh5agfgtdddke8b3a0f6b.xn--p1ai [Wed May 03 06:59:56 2023] [error] [pid 56768] src/server/wsgi_logger.c(147): [client 185.252.250.154:48440]   File "/home/c/ct88349/UnionMasters//venv/lib/python3.6/site-packages/django/apps/config.py", line 224, in create
xn--80aehbh5agfgtdddke8b3a0f6b.xn--p1ai [Wed May 03 06:59:56 2023] [error] [pid 56768] src/server/wsgi_logger.c(147): [client 185.252.250.154:48440]     import_module(entry)
xn--80aehbh5agfgtdddke8b3a0f6b.xn--p1ai [Wed May 03 06:59:56 2023] [error] [pid 56768] src/server/wsgi_logger.c(147): [client 185.252.250.154:48440]   File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
xn--80aehbh5agfgtdddke8b3a0f6b.xn--p1ai [Wed May 03 06:59:56 2023] [error] [pid 56768] src/server/wsgi_logger.c(147): [client 185.252.250.154:48440]     return _bootstrap._gcd_import(name[level:], package, level)
xn--80aehbh5agfgtdddke8b3a0f6b.xn--p1ai [Wed May 03 06:59:56 2023] [error] [pid 56768] src/server/wsgi_logger.c(147): [client 185.252.250.154:48440]   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
xn--80aehbh5agfgtdddke8b3a0f6b.xn--p1ai [Wed May 03 06:59:56 2023] [error] [pid 56768] src/server/wsgi_logger.c(147): [client 185.252.250.154:48440]   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
xn--80aehbh5agfgtdddke8b3a0f6b.xn--p1ai [Wed May 03 06:59:56 2023] [error] [pid 56768] src/server/wsgi_logger.c(147): [client 185.252.250.154:48440]   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
xn--80aehbh5agfgtdddke8b3a0f6b.xn--p1ai [Wed May 03 06:59:56 2023] [error] [pid 56768] src/server/wsgi_logger.c(147): [client 185.252.250.154:48440] ModuleNotFoundError: No module named 'debug_toolbar'
xn--80aehbh5agfgtdddke8b3a0f6b.xn--p1ai [Wed May 03 10:12:32 2023] [error] [pid 65454] core.c(3895): [client 185.252.250.154:55978] AH00124: Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.
xn--80aehbh5agfgtdddke8b3a0f6b.xn--p1ai [Wed May 03 10:23:00 2023] [error] [pid 63272] core.c(3895): [client 185.191.215.99:51560] AH00124: Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.
xn--80aehbh5agfgtdddke8b3a0f6b.xn--p1ai [Wed May 03 10:47:24 2023] [error] [pid 27792] src/server/mod_wsgi.c(3692): [client 185.252.250.154:43172] mod_wsgi (pid=27792): Target WSGI script '/home/c/ct88349/UnionMasters/public_html/wsgi.py' cannot be loaded as Python module.
xn--80aehbh5agfgtdddke8b3a0f6b.xn--p1ai [Wed May 03 10:47:24 2023] [error] [pid 27792] src/server/wsgi_logger.c(630): [client 185.252.250.154:43172] mod_wsgi (pid=27792): Exception occurred processing WSGI script '/home/c/ct88349/UnionMasters/public_html/wsgi.py'.
xn--80aehbh5agfgtdddke8b3a0f6b.xn--p1ai [Wed May 03 10:47:24 2023] [error] [pid 27792] src/server/wsgi_logger.c(147): [client 185.252.250.154:43172] Traceback (most recent call last):
xn--80aehbh5agfgtdddke8b3a0f6b.xn--p1ai [Wed May 03 10:47:24 2023] [error] [pid 27792] src/server/wsgi_logger.c(147): [client 185.252.250.154:43172]   File "/home/c/ct88349/UnionMasters/public_html/wsgi.py", line 14, in <module>
xn--80aehbh5agfgtdddke8b3a0f6b.xn--p1ai [Wed May 03 10:47:24 2023] [error] [pid 27792] src/server/wsgi_logger.c(147): [client 185.252.250.154:43172]     from django.core.wsgi import get_wsgi_application
xn--80aehbh5agfgtdddke8b3a0f6b.xn--p1ai [Wed May 03 10:47:24 2023] [error] [pid 27792] src/server/wsgi_logger.c(147): [client 185.252.250.154:43172] ModuleNotFoundError: No module named 'django'
